name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: pytest
        continue-on-error: true

      - name: Send email notification if tests fail
        if: steps.run-tests.outcome == 'failure'
        env:
          TO_EMAIL: "fake@123.com"
        run: |
          chmod +x send_email.sh
          ./send_email.sh "Nightly Build Failed: Test Cases Failed"

      - name: Fail job if tests failed
        if: steps.run-tests.outcome == 'failure'
        run: exit 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-beyond-CRUD:nightly
